[2025-08-25 13:00:48,240] {processor.py:153} INFO - Started process (PID=2795405) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:00:48,240] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:00:48,241] {logging_mixin.py:115} INFO - [2025-08-25 13:00:48,241] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:00:48,302] {logging_mixin.py:115} INFO - [2025-08-25 13:00:48,302] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:00:48,302] {logging_mixin.py:115} INFO - [2025-08-25 13:00:48,302] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:00:48,303] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:00:48,350] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2025-08-25 13:01:33,718] {processor.py:153} INFO - Started process (PID=2795588) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:01:33,741] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:01:33,741] {logging_mixin.py:115} INFO - [2025-08-25 13:01:33,741] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:01:33,809] {logging_mixin.py:115} INFO - [2025-08-25 13:01:33,809] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:01:33,809] {logging_mixin.py:115} INFO - [2025-08-25 13:01:33,809] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:01:33,809] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:01:33,847] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.132 seconds
[2025-08-25 13:02:22,712] {processor.py:153} INFO - Started process (PID=2795765) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:02:22,734] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:02:22,735] {logging_mixin.py:115} INFO - [2025-08-25 13:02:22,735] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:02:22,797] {logging_mixin.py:115} INFO - [2025-08-25 13:02:22,796] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:02:22,797] {logging_mixin.py:115} INFO - [2025-08-25 13:02:22,797] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:02:22,808] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:02:22,818] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2025-08-25 13:03:18,274] {processor.py:153} INFO - Started process (PID=2795954) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:03:18,285] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:03:18,286] {logging_mixin.py:115} INFO - [2025-08-25 13:03:18,286] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:03:18,338] {logging_mixin.py:115} INFO - [2025-08-25 13:03:18,337] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:03:18,338] {logging_mixin.py:115} INFO - [2025-08-25 13:03:18,338] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:03:18,338] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:03:18,370] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2025-08-25 13:05:43,681] {processor.py:153} INFO - Started process (PID=2796511) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:05:43,704] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:05:43,704] {logging_mixin.py:115} INFO - [2025-08-25 13:05:43,704] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:05:43,772] {logging_mixin.py:115} INFO - [2025-08-25 13:05:43,772] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:05:43,772] {logging_mixin.py:115} INFO - [2025-08-25 13:05:43,772] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:05:43,772] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:05:43,806] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.128 seconds
[2025-08-25 13:06:31,553] {processor.py:153} INFO - Started process (PID=2796654) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:06:31,576] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:06:31,576] {logging_mixin.py:115} INFO - [2025-08-25 13:06:31,576] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:06:31,619] {logging_mixin.py:115} INFO - [2025-08-25 13:06:31,618] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:06:31,619] {logging_mixin.py:115} INFO - [2025-08-25 13:06:31,619] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:06:31,619] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:06:31,652] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2025-08-25 13:08:39,369] {processor.py:153} INFO - Started process (PID=2797161) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:08:39,380] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:08:39,381] {logging_mixin.py:115} INFO - [2025-08-25 13:08:39,381] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:08:39,401] {logging_mixin.py:115} INFO - [2025-08-25 13:08:39,400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:08:39,434] {logging_mixin.py:115} INFO - [2025-08-25 13:08:39,401] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:08:39,434] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:08:39,448] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2025-08-25 13:14:07,605] {processor.py:153} INFO - Started process (PID=2798178) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:14:07,617] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:14:07,617] {logging_mixin.py:115} INFO - [2025-08-25 13:14:07,617] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:14:07,667] {logging_mixin.py:115} INFO - [2025-08-25 13:14:07,666] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:14:07,667] {logging_mixin.py:115} INFO - [2025-08-25 13:14:07,667] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:14:07,667] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:14:07,711] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2025-08-25 13:14:52,750] {processor.py:153} INFO - Started process (PID=2798281) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:14:52,762] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:14:52,762] {logging_mixin.py:115} INFO - [2025-08-25 13:14:52,762] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:14:52,812] {logging_mixin.py:115} INFO - [2025-08-25 13:14:52,811] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:14:52,812] {logging_mixin.py:115} INFO - [2025-08-25 13:14:52,812] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:14:52,812] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:14:52,856] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2025-08-25 13:15:38,806] {processor.py:153} INFO - Started process (PID=2798424) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:15:38,825] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:15:38,825] {logging_mixin.py:115} INFO - [2025-08-25 13:15:38,825] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:15:38,873] {logging_mixin.py:115} INFO - [2025-08-25 13:15:38,872] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:15:38,873] {logging_mixin.py:115} INFO - [2025-08-25 13:15:38,873] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:15:38,873] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:15:38,896] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2025-08-25 13:16:28,364] {processor.py:153} INFO - Started process (PID=2798574) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:16:28,388] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:16:28,388] {logging_mixin.py:115} INFO - [2025-08-25 13:16:28,388] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:16:28,416] {logging_mixin.py:115} INFO - [2025-08-25 13:16:28,416] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:16:28,416] {logging_mixin.py:115} INFO - [2025-08-25 13:16:28,416] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:16:28,417] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:16:28,427] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2025-08-25 13:17:19,771] {processor.py:153} INFO - Started process (PID=2798727) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:17:19,782] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:17:19,783] {logging_mixin.py:115} INFO - [2025-08-25 13:17:19,783] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:17:19,799] {logging_mixin.py:115} INFO - [2025-08-25 13:17:19,799] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:17:19,800] {logging_mixin.py:115} INFO - [2025-08-25 13:17:19,800] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:17:19,800] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:17:19,811] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-08-25 13:18:07,059] {processor.py:153} INFO - Started process (PID=2798844) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:18:07,070] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:18:07,071] {logging_mixin.py:115} INFO - [2025-08-25 13:18:07,071] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:18:07,104] {logging_mixin.py:115} INFO - [2025-08-25 13:18:07,104] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:18:07,105] {logging_mixin.py:115} INFO - [2025-08-25 13:18:07,105] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:18:07,105] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:18:07,132] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2025-08-25 13:18:49,234] {processor.py:153} INFO - Started process (PID=2798976) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:18:49,246] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:18:49,246] {logging_mixin.py:115} INFO - [2025-08-25 13:18:49,246] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:18:49,276] {logging_mixin.py:115} INFO - [2025-08-25 13:18:49,275] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:18:49,276] {logging_mixin.py:115} INFO - [2025-08-25 13:18:49,276] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:18:49,276] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:18:49,298] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-08-25 13:19:40,109] {processor.py:153} INFO - Started process (PID=2799159) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:19:40,120] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:19:40,121] {logging_mixin.py:115} INFO - [2025-08-25 13:19:40,121] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:19:40,168] {logging_mixin.py:115} INFO - [2025-08-25 13:19:40,167] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:19:40,168] {logging_mixin.py:115} INFO - [2025-08-25 13:19:40,168] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:19:40,168] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:19:40,204] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2025-08-25 13:20:29,525] {processor.py:153} INFO - Started process (PID=2799336) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:20:29,536] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:20:29,537] {logging_mixin.py:115} INFO - [2025-08-25 13:20:29,537] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:20:29,575] {logging_mixin.py:115} INFO - [2025-08-25 13:20:29,575] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:20:29,575] {logging_mixin.py:115} INFO - [2025-08-25 13:20:29,575] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:20:29,576] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:20:29,609] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2025-08-25 13:21:16,103] {processor.py:153} INFO - Started process (PID=2799479) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:21:16,126] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:21:16,126] {logging_mixin.py:115} INFO - [2025-08-25 13:21:16,126] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:21:16,164] {logging_mixin.py:115} INFO - [2025-08-25 13:21:16,164] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:21:16,165] {logging_mixin.py:115} INFO - [2025-08-25 13:21:16,165] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:21:16,165] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:21:16,198] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2025-08-25 13:22:00,280] {processor.py:153} INFO - Started process (PID=2799560) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:22:00,290] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:22:00,291] {logging_mixin.py:115} INFO - [2025-08-25 13:22:00,291] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:22:00,307] {logging_mixin.py:115} INFO - [2025-08-25 13:22:00,307] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:22:00,307] {logging_mixin.py:115} INFO - [2025-08-25 13:22:00,307] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:22:00,307] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:22:00,434] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.157 seconds
[2025-08-25 13:22:54,705] {processor.py:153} INFO - Started process (PID=2799742) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:22:54,716] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:22:54,717] {logging_mixin.py:115} INFO - [2025-08-25 13:22:54,717] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:22:54,733] {logging_mixin.py:115} INFO - [2025-08-25 13:22:54,733] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:22:54,733] {logging_mixin.py:115} INFO - [2025-08-25 13:22:54,733] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:22:54,734] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:22:54,756] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2025-08-25 13:23:44,615] {processor.py:153} INFO - Started process (PID=2799920) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:23:44,638] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:23:44,638] {logging_mixin.py:115} INFO - [2025-08-25 13:23:44,638] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:23:44,678] {logging_mixin.py:115} INFO - [2025-08-25 13:23:44,677] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:23:44,678] {logging_mixin.py:115} INFO - [2025-08-25 13:23:44,678] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:23:44,678] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:23:44,709] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2025-08-25 13:24:46,670] {processor.py:153} INFO - Started process (PID=2800119) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:24:46,682] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:24:46,682] {logging_mixin.py:115} INFO - [2025-08-25 13:24:46,682] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:24:46,699] {logging_mixin.py:115} INFO - [2025-08-25 13:24:46,698] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:24:46,699] {logging_mixin.py:115} INFO - [2025-08-25 13:24:46,699] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:24:46,699] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:24:46,721] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2025-08-25 13:25:44,160] {processor.py:153} INFO - Started process (PID=2800310) to work on /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:25:44,172] {processor.py:641} INFO - Processing file /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-08-25 13:25:44,172] {logging_mixin.py:115} INFO - [2025-08-25 13:25:44,172] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:25:44,189] {logging_mixin.py:115} INFO - [2025-08-25 13:25:44,189] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-08-25 13:25:44,189] {logging_mixin.py:115} INFO - [2025-08-25 13:25:44,189] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-08-25 13:25:44,189] {processor.py:653} WARNING - No viable dags retrieved from /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-08-25 13:25:44,238] {processor.py:161} INFO - Processing /root/Documents/airflow/venv/lib64/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
